name: bs-log pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Yarn cache
        id: print-yarn-cache
        run: echo "::set-output name=yarn-cache::$(yarn cache dir)"

      - name: Restore Yarn cache
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.print-yarn-cache.outputs.yarn-cache }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn deps
        run: yarn install

      - name: Build BuckleScript lib
        run: yarn run build

  rc:
    needs: build
    name: Prepare RC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Move lib files
        run: |
          mkdir -p _release/src
          cp README.md _release/README.md
          cp bsconfig.json _release/bsconfig.json
          cp src/BrowserLogger.re _release/src/BrowserLogger.re
          cp src/NodeLogger.re _release/src/NodeLogger.re
          node .github/workflows/scripts/write-package-json.js

      - name: Upload release
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: _release
